services:
- name: prism-ui
  externalPort: '80'
  internalPort: '80'

ingress:
  enabled: true
  internet_facing: true
  authentication:
    employee: true
  production-names:
    release-admin:
    - prism.internal.rexchange.com
    - prism.rex.sh

readinessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 5
